CLASS zcl_06_log_c426 DEFINITION INHERITING FROM zcl_05_log_c426
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_06_log_c426 IMPLEMENTATION.
ENDCLASS.
